### ISSUE TITLE
issues with ensemble.thresh

### ISSUE THREAD

**Issue by jamesrlawson** [sylvainschmitt/SSDM#9] opened 2017-09-20 01:45 UTC
Hi Sylvain,

I've been playing around with your SSDM package for a couple of weeks now and really appreciate all the work you have put into it. I am trying to create an SSDM for around 1000 plant species, using just Maxent. 

I have come across some problems with thresholding. When I set leave the ensemble.thresh at its default of 0.7, and AUC as the metric, I get an error message saying that there are less than 2 models left in the ensemble and perhaps I should try an easier thresholding. This implies to me that I have no models in my stack which have AUC > 0.7, and this is not the case (they're all between 0.68 and 0.73).

If I use a value of 0 for ensemble.thresh I can get the code to run, but the diversity model it produces looks very poor.

Here is the command I'm running:

SSDM.asia <- stack_modelling(algorithms = c('MAXENT'), Occurrences = lianas.asia,
                                Env = env.asia, Xcol = 'longitude', Ycol = 'latitude', Spcol = 'species', 
                                method = "pSSDM", rep = 1, verbose = TRUE, ensemble.thresh = 0, cores = 4, save=TRUE)

Perhaps you have some suggestions for me? 

It seems like the problem comes at the very end, when the function attempts to stack all the Maxent models. I have saved the output of stack_modelling, and it would be really useful if I could load up the individual species models, perhaps using stacking(), so I could tweak the way the stack is created without having to leave my computer running overnight calculating all the individual SDMs.

I have also noticed that the individual SDMs are somewhat different to those I obtain passing the same data to dismo::maxent. I'm just doing a run through dismo::maxent for all my species now, so I can give you a table comparing the outputs if that might be helpful.

Thanks so much for you help,
James

**Comment by jamesrlawson** [comment] 2017-09-20 02:11
This is the probability raster for the species Parsonsia straminea, produced by SSDM::stack_modelling()

![image](https://user-images.githubusercontent.com/6722981/30623661-45f20c2e-9dfc-11e7-8509-65b316e258ae.png)

This it the equivalent raster produced using dismo::maxent (logistic output)

![image](https://user-images.githubusercontent.com/6722981/30623713-ababc442-9dfc-11e7-91b5-642c59a480f7.png)

I'm pretty familiar with this species and the dismo::maxent output is much more believable.

Any idea what might be going on?

Thanks again

**Comment by sylvainschmitt** [comment] 2017-09-20 07:06
Hello James,

And thank your for the compliment. Apparently you have to different issues and I will treat them separately : (1) AUC threshold with maxent algorithm, (2) difference of probability prediction between maxent algorithm in `SSDM` or in `dismo` package.

I will start with the second issue because you'll have to seek for the answer. In fact `SSDM` package to call the maxent program uses itself the `dismo` package (see [get_model function](https://github.com/sylvainschmitt/SSDM/blob/master/R/project.R)). So regarding the algorithm it is entirely the same. Consequently if there are differences it's due to the algorithm parameters. `SSDM` set some parameters to their default values and allow you to tune some of them for each algorithm. Regarding maxent the options you can set in `SSDM` are number of trees and final leave size. So effectively if when you used `dismo` you used other parameters you could get slightly different results. Could you give me the precise command and parameters you make for `dismo::maxent` ?

I'll answer your first issue in another comment.

**Comment by jamesrlawson** [comment] 2017-09-20 07:20
Hello Sylvain,

Thanks for getting back to me so swiftly!

I was aware that get_model calls dismo::maxent, so I was quite confused. Here's the command and parameters I give to dismo::maxent:

`model.me <- maxent(env, current_species_occ, args=c("-J", "-P", 'threads=8'))
`

As I understand it, the -J and -P arguments simply add some evaluation analyses, but don't alter the model itself.

**Comment by sylvainschmitt** [comment] 2017-09-20 07:21
Concerning your first problem, first off all yes you can use the `stack_modelling` output to do a new stack with the `stacking` option simply by calling it on the ensemble models of the stack : `do.call("stacking", stack@enms)`.

Regarding the AUC threshold issue, could you set the threshold to 0 and give me a table of the AUC of each ensemble models (in order to see if there is really a bug or not) ? Just for you to know the threshold is used as strictly inferior, meaning all models AUC < 0.7 are rejected (see [sum function](https://github.com/sylvainschmitt/SSDM/blob/30dfe359f1f2c34fa6a73e048ba499b9e98c9d30/R/ensemble.R)). But truly it might be possible that with given parameters and data maxent poorly performed and you don't have good quality ensemble models. Have you tried with different algorithm (i.e. maxent, SVM and glm) ?

I'm waiting for your answers, hoping to solve the issue.

**Comment by sylvainschmitt** [comment] 2017-09-20 07:32
Effectively You are using three arguments : 

responsecurves | P | boolean | false | Create graphs showing how predicted relative probability of              occurrence depends on the value of each environmental variable
-- | -- | -- | -- | --



jackknife | J | boolean | false | Measure importance of each environmental variable by training with              each environmental variable first omitted, then used in isolation
-- | -- | -- | -- | --



threads |   | integer | 1 | Number of processor threads to use. Matching this number to the              number of cores on your computer speeds up some operations,              especially variable jackknifing.
-- | -- | -- | -- | --


And effectively none of them should change the model itself, so it means models are running the same way. The only last thing I can thin of is the use of categorical variable, are you using some ?

And if not in which way both models differ (maxent with SSDM or maxent with dismo) ?

**Comment by jamesrlawson** [comment] 2017-09-20 07:36
Re: do.call("stacking", stack@enms): Right, I see how that works. If I have the stack saved (using save=TRUE in stack_modelling,) what is the best way to load it back into my environment? I have since had to restart the R and wiped my environment.

**Comment by sylvainschmitt** [comment] 2017-09-20 07:39
`SSDM::load_stack()` function or through the load data > previous model in the interface

**Comment by jamesrlawson** [comment] 2017-09-20 07:41
Here is a table of the AUCs for each ensemble model:
[AUCs_SSDM.xlsx](https://github.com/sylvainschmitt/SSDM/files/1316932/AUCs_SSDM.xlsx)

Ah, thank you, I was looking in the SSDM/R directory for load_stack because I was sure I'd seen it

**Comment by sylvainschmitt** [comment] 2017-09-20 07:55
The result of SDMs depend on the species occurrences location but also on the environmental variables used. Did you have a look on which variable was driving the model and its "distribution" regarding occurrences of your different species ? And once again I recommend the use of multiple algorithms because depending on the situation they will well or poorly work.

Concerning the AUC it appears they are all close to 0.7 but above 0.7, so if the threshold is really set to 0.7 most of models should be kept (besides it is a pretty low threshold resulting effectively in poor projection). Could you give me the command you use to set the threshold to 0.7 ? Are you sure it was not at the default value of 0.75 which would result in no model kept. And did you took care of the bit tricky way to set ensemble.metric and ensemble.threshold (because you can give more than one threshold) ?

**Comment by jamesrlawson** [comment] 2017-09-20 08:00
Thanks for the advice, at the moment I am just using Maxent, because we are comparing its output with a couple of other models, including gradient boosting. My colleague has a bespoke method for comparing the models though, although I'll look into the method implemented in SSDM once I get things running properly.

Sure, I used:

`SSDM.asia <- stack_modelling(algorithms = c('MAXENT'), Occurrences = lianas.asia,
                                Env = env.asia, Xcol = 'longitude', Ycol = 'latitude', Spcol = 'species', 
                                method = "pSSDM", rep = 1, verbose = TRUE, ensemble.thresh = 0.7, cores = 4, save=TRUE)`

Is this the correct approach?

Also, I just tried using modelling() to run a model for just one species, and obtained a similar (looks the same) output to the model I created using dismo::maxent. So it appears that something strange is happening with models that are being created in stack_modelling.

**Comment by sylvainschmitt** [comment] 2017-09-20 08:13
Shouldn't happen because modelling, ensemble_modelling and stack_modelling are built as Russian doll. Still it might possible that a parameter is badly transferred from one level to the other (because when you call stack modelling parameters follow the following path stack > ensemble > modelling). So I will look deeper into it,especially if we are truly facing a bug here. But in order to do that I will come back to you later.

**Comment by jamesrlawson** [comment] 2017-09-20 08:17
Just checked, ensemble_modelling produces a good model too. Thank you again for your help - if there's anything else I can assist with please let me know.

**Comment by sylvainschmitt** [comment] 2017-09-20 08:25
I'm glad you are offering your help ! If you have the time and the courage to look into it I can give you few leads. So regarding your own tests the issue is between stack_modelling and ensemble_modelling, that is an important information. 
* First thing you can test is if the issue is coming from stacking (called by stack_modelling) or is just inside stack_modelling by realizing directly a simple SSDM with stack modelling or stacking the same simple SSDM obtained with multiple call to ensemble_modelling and stacked with stacking
* If the issue is not coming from stacking you can look into the transition of parameters from stack_modelling to ensemble_modelling in stack_modelling function [code](https://github.com/sylvainschmitt/SSDM/blob/master/R/stack_modelling.R) from line 329 to 429.

Keep me informed if you find clues, thank you and good luck.

**Comment by jamesrlawson** [comment] 2017-09-20 08:36
Happy to dive into the code, and report what I find. Will leave it for tomorrow though as it's 18:35 here and I have some things to organise here before I can go home. 

Have a good day, 
James.

**Comment by jamesrlawson** [comment] 2017-09-22 02:04
Hi Sylvain,

The issue appears to be within stack_modelling. I created some models using `ensemble_modelling` and they were similar/the same as those I created using `dismo::maxent`. I could use `stacking` to put them together with no problems. 

When I tried to create the same models in a stack using `stack_modelling` the models were incorrect.
Will try and get to looking into the code early next week.

As I side note, I was trying to work out how to create an SSDM using 
 `stacking` with hundreds of models. I wasn't able to use hundreds of arguments to `stacking`, and saving the models in a list and then using `do.call('stacking', my.list)` did not work. Is there an approach you'd recommend?

**Comment by sylvainschmitt** [comment] 2017-10-17 11:35
For the second question, you mean that you could not put both hundreds of models and their arguments ? What I am doing is to concatenate arguments ,explicitly named, and the list of models. For example if I want to stack a list of ESDM with the pSSDM method I will write `do.call('stacking', c(ESDM.list, method = 'pSSDM'))`. You can also do it in different times by adding arguments to your list and then call the stacking: `ESDM.list['method'] <- 'pSSDM'` and then `do.call('stacking', ESDM.list)`.

Regarding the main issue that is apparently due to the use of either ensemble_modelling or stacking inside the the stack_modelling function, I can't find the issue or repeat the bug. Could you create a minimal example with the dataset included in the package (`data(Env)` and `data(Occurrences)`) ?

**Comment by sylvainschmitt** [comment] 2018-03-22 08:11
Hello again, sorry to come back so late to the issue. But I am not able to reproduce the error could you give me a minimal example in order to help me debug the issue ?

**Comment by jamesrlawson** [comment] 2018-03-22 08:39
Hi Sylvain,

Sorry to not reply to your last message. I'm pretty flat out working for a
deadline at the moment but I'll try to get back to you in the next couple
of weeks.

Cheers,
James

--

James Lawson
Research Fellow,
Department of Biological Sciences
Macquarie University, Sydney

**Comment by sylvainschmitt** [comment] 2018-03-30 07:08
I tried and could not reproduce the error with a minimal example, I think the issue might come from the way you are using `dismo::maxent`, did you correctly used the same pseudo-absence than `stack_modelling` ? If not it would explain the difference you obtain.

**Comment by sylvainschmitt** [comment] 2018-04-20 09:13
Hello, I can't reproduce the error, and I have currently lot of users using stack modeling without reporting any similar bug. Consequently I am currently afraid that the issue is coming from your side. As a conclusion, because the issue is starting to be old, I will close the thread if you are not able to provide a minimal example for the bug. Anyway, that is not an end, because if you manage to have a minimal example for me to reproduce the putative error or bug, I will be happy to reopen the issue.

**Closed** 2018-06-20 20:15 UTC

**Comment by Eric56-SDM** [comment] 2023-08-24 15:35
Hello, my name is Eric and I am doing a research project creating Species Distribution Models using single modelling algorithms, ensemble modelling, and then my final goal is to create a "Community Distribution Model" incorporating multiple species which seems possible using a "predict then assemble" strategy via the SSDM package and stack_modelling function. I have two questions. 


1. Based on the description of the stack_modelling function is the only way to incorporate multiple species occurrence data points via the "occurrence" argument of this function? Thus far I have been dabbling with incorporating multiple species in a .csv file arranged with columns of species name, Longitude, Latitude. This appears to be the only method of incorporating multiple species data into a combined csv file, but please let me know if any other methods are possible. 

2. Second question: as I am attempting to develop a "Community Level Model" using multiple species I have been using the stack_modelling function, and have recieved the following error when attempting to run the code:  "Error in stack_modelling(c("all"), datafile, variable.stack, rep = 1  :  Less than two species models were retained, you should lower the ensemble threshold value (ensemble.thresh parameter)." Based on the discussion above, I have tried lowering the threshold value, and still receive the same error. My variable "datafile" contains my presence data and "variable.stack" includes my predictor variables. Please advise. 


# image of error. 
<img width="977" alt="Image 1" src="https://github.com/sylvainschmitt/SSDM/assets/143107097/b2b8384b-7da9-4796-8467-9691d43701be">
