### ISSUE TITLE
Warning in file.info(files) :

### ISSUE THREAD

**Issue by dpoursanidis** [sylvainschmitt/SSDM#8] opened 2017-09-11 14:07 UTC
Hi folks

I want to try your new SSDM package.
While opening the gui and trying to navigate for data and rasters i recieve the following error in the console

Warning in file.info(files) :
  cannot open file 'F:/System Volume Information': Access denied

This is the first time in r i recieve such an error. Any idea on ?

**Comment by sylvainschmitt** [comment] 2017-09-11 14:17
Hi,

With that level of information, I can't say much. But if I had to guess, I supposed it might be linked to the fact that you are trying to open a file from a disk on a network or maybe in USB. I don't exactly remember but I my memory the gui does not accept to work with files on the network.

Could you give me more informations about what is exactly this F disk on your system ?

**Comment by dpoursanidis** [comment] 2017-09-11 14:20
Hi 

F:/ is a physical based HDD in my PC. No USB nor network based data.
The same message appear in C, D, E. When i only move data in "my documents" under c, i could use the SSDM.
Which are the limitations of GUI in terms of ram ?

Best
D.

**Comment by sylvainschmitt** [comment] 2017-09-11 14:29
Strange !

You are working with windows so. And what are your account access rights to your device ? I mean could you normally open F without special rights ?

Because for windows users SSDM interface offers to start with "my documents", "example" folders and all roots of your system detected with ` system('wmic logicaldisk get caption', intern = TRUE)`  command. So apparently they appear in your interface but you can't access them. Could you send a screenshot of the console when the bug appears on the interface ? Anyway unfortunately this seems link to a dependency, [shinyFiles](https://github.com/thomasp85/shinyFiles) that I use to deal with file navigation in the interface. So we will see what we could do, but it might be coming from the dependency and not SSDM.

Regarding the RAM it's the same amount than in you regular R session. Only parallel computing is blocked in the interface. But if you think you'll risk to have heavy computing, I'll advice to use command instead of the interface.

**Comment by dpoursanidis** [comment] 2017-09-13 08:10
Hi,

Opening the GUI you can see the following commands to appear in the console
![image](https://user-images.githubusercontent.com/8640644/30364893-b66a4054-986e-11e7-8d52-290a497f2c02.png)

Then, i locate d hdd and see what messages appear in the console

![image](https://user-images.githubusercontent.com/8640644/30366545-11814d8e-9874-11e7-80d3-b659650ebe99.png)

**Comment by sylvainschmitt** [comment] 2017-09-13 08:14
Ok, but I see only warnings that says R can't access the hard drive information, but does that mean you can't navigate inside the hard drive ? I mean once in this tep can't you open Gis DataBase for instance ?

**Comment by dpoursanidis** [comment] 2017-09-13 08:16
It didn't allow me to navigate in the D, F, C HDD's of the PC. Only in the "my doc's" file.

**Comment by sylvainschmitt** [comment] 2017-09-13 08:20
You mean that if you select any folder of the previous screenshot by double clicking them they won't open even if you let enough time to the interface to load what it contains ?

And for your information, even if I know it is not a true solution to the issue, `gui` function include the `working directory` parameter to launch the interface in a desired folder set at the current working directory by default.

**Comment by dpoursanidis** [comment] 2017-09-13 08:36
Exactly that.

I will do this way, but in a next release please fix it. Have you face similar issues ?

**Comment by sylvainschmitt** [comment] 2017-09-13 08:41
No I never encountered this issue before but I know that opening a folder with numerous sub-folders can take time. And once again I can't fix it due to the fact that the issue is happening inside the ` shinyFiles` dependency. So I will signal it to its developer. And in next release I can only hope for a fix of ` shinyFiles` or move to another dependency to deal with file selection inside the shiny interface.

**Comment by sylvainschmitt** [comment] 2017-09-13 08:45
Which version of R are you using ? 
if you are using the 3.4 version you might want have a look to this : https://github.com/thomasp85/shinyFiles/issues/57

**Comment by dpoursanidis** [comment] 2017-09-13 08:50
yeap, 3.4 ... i will change and test and come back. Also, consider add a read shapefile function in addition to .csv

**Comment by sylvainschmitt** [comment] 2017-09-20 06:46
Due to the fact that the issue is linked to a dependency I'm closing it.

**Closed by sylvainschmitt** 2017-09-20 06:46 UTC
Labels: bug, wontfix
