### ISSUE TITLE
load_var() overwrites temporary files whan environmental variables have the same name

### ISSUE THREAD

**Issue by sylvainschmitt** [sylvainschmitt/SSDM#31] opened 2018-06-20 20:11 UTC
As spotted by @fernandezmiguel the temporary files are overwriting themselves if environmental variables from different folders have the same name causing trouble especially for model forecasting:
https://github.com/sylvainschmitt/SSDM/blob/f10c2c9302941e5abba0238032b0642d71ebe318/R/load_var.R#L173-L179
A fix would be to include the system date in the temporary files name but it would result in multiplication of temporary files when reading several times the same files.

**Comment by lukasbaumbach** [comment] 2019-10-16 10:20
Just a suggestion: We might also think about including the option to manually set the directory where the temporary files are stored (e.g. `tmp.dir`). Since the temporary files can get quite large, it may be undesirable to spam the R folder, but give a different location which may have more memory to spare.

**Comment by sylvainschmitt** [comment] 2019-10-16 11:43
> Since the temporary files can get quite large, it may be undesirable to spam the R folder, but give a different location which may have more memory to spare.

Yes that's why it isn't the case ! Temporary are logically in the temporary folder of the OS as previously discussed in #51 

https://github.com/sylvainschmitt/SSDM/blob/714b83a0d5bc5bf21ab09445988837aab24b7c8d/R/zzz.R#L5-L9

**Comment by lukasbaumbach** [comment] 2019-10-21 09:07
In my case the problem is, that the tmp folder is on my system partition (I think this is common). As a consequence, my computer almost crashed, when I set tmp=TRUE. The same happened to me when working on a cluster (where each machine has a 2TB hard disk) and quickly killed my job because it was out of memory. 

In these situations it may be preferable to set the tmp directory to another location, which can deal with the data load.

**Comment by sylvainschmitt** [comment] 2019-10-21 11:08
Ok so let's set `tmp` either to a `logical` to save or not temporary files in the temporary folders of the OS or a to a `character` to set a path were the user can reroot temporary files:

tmp   logical or character.  If set to true, the habitat suitability map of each algorithms is saved in the  R environment temporary folder to release memory. If set to a folder path the habitat suitability map of each algorithms is saved in the defined folder. But beware: if you close R, temporary files will be deleted. To avoid any loss you can save your SSDM with save.model. Depending on number, resolution and extent of models, temporary files can take a lot of disk space. 

Another solution is to reroot your R environment temporary files before loading SSDM: https://stackoverflow.com/questions/17107206/change-temporary-directory .

**Comment by lukasbaumbach** [comment] 2019-10-21 13:25
Sounds good to me!

I didn't know the rerooting was possible. Seems like it's completely feasible without the fix then, although in general I like "inside-package" solutions more than changing global settings.

**Comment by lukasbaumbach** [comment] 2020-04-06 13:51
fixed in new version

**Closed by lukasbaumbach** 2020-04-06 13:51 UTC
Labels: bug
