### ISSUE TITLE
Temporary files issue in `stack_modelling` with Mac

### ISSUE THREAD

**Issue by keefer56** [sylvainschmitt/SSDM#51] opened 2019-06-15 08:55 UTC
Closing clusters 
There were 50 or more warnings (use warnings() to see the first 50)
There were 50 or more warnings (use warnings() to see the first 50)
#### Species stacking with ensemble models ##### 

Stack creation... 
Error in file(fn, "rb") : cannot open the connection
In addition: Warning messages:
1: In for (v in val) { : closing unused connection 4 (<-localhost:11539)
2: In for (v in val) { : closing unused connection 3 (<-localhost:11539)
3: In file(fn, "rb") :
  cannot open file '/private/var/folders/z3/f3_sw2rn1bld951klh2k66zm0000gn/T/Rtmp08BDR9/raster/r_tmp_2019-06-14_142056_27007_50252.gri': No such file or directory
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
In addition: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by keefer56** [comment] 2019-06-15 08:59
Hello Sylvain,

Thanks for the fix yesterday. I now am running into this issue? Are these related somehow or do you have any advice to overcome this?

**Comment by keefer56** [comment] 2019-06-17 09:19
Hi Sylvain,

Somehow I managed to close this issue

**Comment by sylvainschmitt** [comment] 2019-06-17 09:37
It seems you have an issue of temporary files with your cluster. Projection rasters of ESDMs are supposed to be saved in temporary files to release RAM and they are read again at the stacking stage. But it appears that the temporary files is inaccessible in this step on your cluster:
> '/private/var/folders/z3/f3_sw2rn1bld951klh2k66zm0000gn/T/Rtmp08BDR9/raster/r_tmp_2019-06-14_142056_27007_50252.gri'
Did you used the option save = T or F ? Do you run it or your personal computer or not ? It's a bit hard for me to solve the issue without knowing the detail of your configuration. Anyway, a workaround if you don't find the origin of the issue is either to save the ESDMs with save = T or to create the stack in two step (ensemble_modelling + stacking, which is actually what stack_modelling do but apparently your temporary files are messing with it).

**Comment by keefer56** [comment] 2019-06-19 07:46
Thank you for the suggestions. Meanwhile my supervisor has run the same data and session on a University Windows PC without any problem. I was using my MacBooks so is this possibly a Mac issue only ?

**Comment by sylvainschmitt** [comment] 2019-06-19 08:24
@keefer56 , yes it's an important detail ! And I'm sorry but the `SSDM` package is supposed to work on Mac but has not been tested intensively on it. Apparently it's globally working on Mac, but maybe not perfectly with temporary files (the issue it seems you encountered). I do not have the time to fix it. So maybe use one of my two work around.

**Comment by lukasbaumbach** [comment] 2019-09-24 12:01
Ok, after a little search, here's my theory of what's going on:
the raster package writes rasters to temporary files, if the rasters cannot be loaded into memory (remember besides your "hard" RAM limit, R has a predefined maximum memory use limit) and no object filename is provided ([also see here](https://www.rdocumentation.org/packages/raster/versions/3.0-2/topics/rasterTmpFile)). The temporary files are cleared every time a new R session is started. If running in parallel, a new session is started for each core in use, so that by the time the code reaches the `ensemble` or `stacking` step these temporary files have already been removed and accordingly their connection is lost.

In my case, `ensemble_modelling` and `stack_modelling` worked, if I either did not use parallelization on my rather large data set or used the small test data set provided in SSDM. Most likely, the first case worked, because no new session was started, while the second case worked, because there was enough memory left to load the rasters directly into memory.

To avoid this issue, there are two possibilities:
- force the raster package to load all rasters into memory using `readAll` (this may be dangerous, however, if memory is limited and may lead to additional crashs)
- write rasters to a different directory than the temporary one if going parallel. From there, they could be read safely for the `ensemble` and/or `stacking` step. This behaviour should be enabled by default if the `cores` argument is >1 and could be set manually by the `tmp` argument. If TRUE, a new directory would be created e.g. in the working directory and possibly also deleted again after the code finished (using `file.remove`).

What do you think @sylvainschmitt ?

**Comment by sylvainschmitt** [comment] 2019-09-24 13:31
Ok that's why I never encountered the error, if you set `tmp` to `TRUE` rasters are written in the temporary files of  `SSDM`, or did I missed something @lukasbaumbach  ? Your first possibility is not feasible, we never use `readAll` because users don't always have the necessary memory (not everybody is working with HPC !). And for me the second is almost implemented, `tmp` already exists. The thing is how do you determined whan to activate `tmp` automatically or not ? Because in some case it's not needed, and forcing writing of files for HPC will be a loss of time. I think we should better catch the error and send a `stop` to the user explaining he should use `tmp` because he doesn't have enough memory to work with all rasters in memory. Anyway, be careful with the temporary files writing because CRAN have restricted policy on that part (and I agree, I find all packages writing temporary files in your folder annoying). And if you implement temporary files writing use the temporary folders of the packages which is in `SSDM` global options : https://github.com/sylvainschmitt/SSDM/blob/master/R/zzz.R . Because you shouldn't write temporary files in the working directory. OS include a temporary files architecture not for nothing, that way if R crash the file will be cleaned at a point by the OS.

**Comment by lukasbaumbach** [comment] 2019-09-24 14:06
Oh alright, I didn't know SSDM creates a separate temporary directory on loading. All the better! 
So is `tmp` working for all associated functions? I think there still is no implementation for `modelling`. I'm also not sure, if there could be problems with overwriting, when models are run in parallel.

Nevertheless I agree, that this "file spamming" behaviour should not be activated by default and be left to the user. I can try including an error catch.

**Comment by sylvainschmitt** [comment] 2019-09-24 15:16
Yes few hidden things happened in background with `SSDM`, you can have a quick look to the [side effect paragraph](http://r-pkgs.had.co.nz/r.html) in Hadley Wickham book to better understand this `zzz.R` file (it's a standard naming, not a fancy name I chose). Does the `modelling` step needs rasters writing ? No there isn't yet, but I didn't thought it was needed. But effectively we may reassess where it's needed or not. And regarding overwriting if the thing is correctly designed, there should be no bugs, and that's almost the case for the moment (except for #31), but if we are expanding temporary files we should effectively take care.

**Comment by lukasbaumbach** [comment] 2020-04-06 13:55
fixed in newest version

**Closed by lukasbaumbach** 2020-04-06 13:55 UTC
