### ISSUE TITLE
Question about stack_modelling use

### ISSUE THREAD

**Issue by nikhailarum** [sylvainschmitt/SSDM#17] opened 2018-02-21 08:28 UTC
Hi Sylvain

I have finally been able to get the cluster to read my GIS data and occurrence data correctly. However when running the `stack_modelling` function I get a number of errors relating to the cluster. This is the code I am using for the `stack_modelling` function:

`SSDM <- stack_modelling(c("GLM", "GAM", "MARS", "GBM", "RF", "CTA", "MAXENT", "ANN", "SVM"), Occurrences, Env, Xcol = "decimallon",
                        Ycol = "decimallat", Pcol = NULL, Spcol = "species", rep = 1,
                        name = "Stack", save = TRUE, path = getwd(), PA = NULL,
                        cv = "holdout", cv.param = c(0.75, 1), thresh = 1001,
                        axes.metric = "Pearson", uncertainty = TRUE, tmp = TRUE,
                        ensemble.metric = c("AUC", "Kappa", "sensitivity", "specificity"), ensemble.thresh = c(0.75, 0.75, 0.75, 0.75), weight = TRUE,
                        method = "bSSDM", metric = "SES", range = NULL,
                        endemism = NULL, verbose = TRUE, GUI = FALSE, cores = 125)`

In return I get a number of errors which I am struggling to interpret:

`Error in checkForRemoteErrors(val) : 
  19 nodes produced errors; first error: comparison of these types is not implemented
Calls: stack_modelling ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
In addition: Warning message:
In eval(e, x, parent.frame()) :
  Incompatible methods ("Ops.data.frame", "Ops.factor") for "=="
Execution halted`

This happens immediately after console states that it is exporting environment to clusters. I understand that on this run I may have allocated more cores than I am allowed however the same error message crops up when I allocate just a fraction of those cores (19). I doubt the issue is with any dataset as my rasters and occurrence data are read correctly in the environment and return the correct values. I am not sure what this error is trying to tell me or indeed how to fix this issue. With your experience of working with the package on an HPC I was hoping you could point me in the right direction as to how I could solve this error. Is this due to the cluster not recognizing which variables to export? Do i need to insert another function to fix this issue?

Many Thanks
NIkhail

**Comment by sylvainschmitt** [comment] 2018-03-22 08:00
Following mail exchanges, it appears that the issue is not coming from the cluster. So could you give more detail about what happen on your local machine ? Or close the issue if you solve the problem.

**Comment by nikhailarum** [comment] 2018-03-22 08:50
Hi Sylvain

On my local machine I get the exact same error message as on the cluster.
The same error message pops up when use the gui interface to run the
analyses. I haven't had as much time to play with this issue as I would
like as I have been busy this week, and have had laptop issues.

Regards
Nikhail

**Comment by sylvainschmitt** [comment] 2018-03-30 06:44
Any update on the issue in order to close it or help you ?

**Comment by nikhailarum** [comment] 2018-03-30 06:54
Hi Sylvain

Sorry for the lack of feedback. I have taken my analyses in a different
direction and I am not using a niche modelling approach for my thesis
anymore. However, when I have some spare time I will continue to try
different solutions. All I can say is that when I tried it on my personal
laptop with just the two species I got the exact same error message as on
the cluster. However it doesn't tell me anything more specific in the error
message.

Thanks,
Nikhail

**Comment by sylvainschmitt** [comment] 2018-03-30 06:55
Ok so I am closing the issue now but don't hesitate to reopen it in case of need

**Closed by sylvainschmitt** 2018-03-30 06:55 UTC
Labels: question

**Comment by nikhailarum** [comment] 2018-03-30 06:57
That's perfect thanks Sylvain

**Comment by grenyer** [comment] 2018-04-10 17:08
Hi Sylvain - I've run into the same issue. Could you summarise either here or by email (grenyer@gmail.com) anything I should know from your discussions with nikhailarum above? It might save some time in the debugging...

**Comment by sylvainschmitt** [comment] 2018-04-11 17:50
Hello, what type of model are you building ? Are you specifically using PPR.MEM ? Because another user spotted a bug that I corrected on GitHhub but which is still not on CRAN. Try to install the package from CRAN with following command and see if the bug persist:

devtools::install_github("sylvainschmitt/SSDM")

Let me know how it goes.
