### ISSUE TITLE
Projection into future

### ISSUE THREAD

**Issue by AJ-KBA** [sylvainschmitt/SSDM#112] opened 2021-08-09 13:51 UTC
Dear Sylvain Schmitt: I ran an ensemble model using the current scenario layers and I wish to project it to the future scenario. 
My codes for current scenario:

EN_CUR <- ensemble_modelling (algorithms='all', Occurrences=subset(Occ, Occ$Common.Name == especie),
                            Env=Current, Xcol = 'lon',Ycol = 'lat', Pcol = 'Pres_abs', rep = 1,
                            name=paste0(especie,"_CUR"),path = 'RESULTS', cv = 'holdout', cv.param = c(0.7,1),
                            metric = 'TSS', axes.metric = 'Pearson',uncertainty = TRUE,
                            ensemble.metric= 'AUC',ensemble.thresh = 0.60, weight = TRUE, verbose = FALSE, tmp = FALSE)

I am able to successfully run the ensemble and save the rasters 
My codes for projection into future:

EN_A45 <-project(obj=EN_CUR, Env=ACC45)

#Current and ACC45 are raster stacks for current and future scenarios, respectively.
#EN_CUR is an object of class Ensemble.SDM

However it gives me following error:

Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'maxent': argument "Env" is missing, with no default

I ran 'ensemble_modelling' with algorithms other than Maxent and I could get the projection raster.
I am using R version 4.0.3 and SSDM_0.2.8 

Thank you.

**Comment by lukasbaumbach** [comment] 2021-08-11 15:04
Hi,

this is a known error (#70), but should have been fixed in the latest version. Did you try installing the latest package version from Github?

**Comment by AJ-KBA** [comment] 2021-08-12 03:42
> Hi,
> 
> this is a known error (#70), but should have been fixed in the latest version. Did you try installing the latest package version from Github?

I used SSDM_0.2.8 which is the latest version available.

**Comment by lukasbaumbach** [comment] 2021-08-12 09:17
Hmm... have you tried doing the same with the example data sets included in SSDM? I just ran a quick test using them and everything worked as supposed. And maybe try using the `modelling` function first to check it's working as intended (everything else builds on top of that). If nothing helps, you would need to give us a minimal working example at least to have something to work with

**Comment by AJ-KBA** [comment] 2021-08-13 04:53
> Hmm... have you tried doing the same with the example data sets included in SSDM? I just ran a quick test using them and everything worked as supposed. And maybe try using the `modelling` function first to check it's working as intended (everything else builds on top of that). If nothing helps, you would need to give us a minimal working example at least to have something to work with

I ran the example data. When I set algorithm = 'all' or algorithm = 'MAXENT' in ensemble_modelling, and then project it to future using the command ''... I get the error - "Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'maxent': argument "Env" is missing, with no default".
However, when I use all 8 algorithms except MAXENT in ensemble_modelling, it works fine and I get the projection layer for future raster stack.

When I set algorithm = 'MAXENT' in the function 'modelling', I get the model. But when I project it to future raster layers, the result is exactly the same as original input SDM@projection..

I am adding subset of my files (Occurrence records, current and future layers - 300kb).  
https://drive.google.com/file/d/1hAlXyaebvgZDR6ZvSY7vT0mkzaEIfRdK/view?usp=sharing

**Comment by lukasbaumbach** [comment] 2021-08-13 08:52
I ran the models again with your data, but still - everything works! Here's what I did, maybe you can find any discrepancies to your coding...

```
library(devtools)
install_github("sylvainschmitt/SSDM")

library(SSDM)
library(raster)
pres <- stack(list.files("SSDM_TRIAL/CURRENT/",pattern=".asc",full.names=TRUE))
fut <- stack(list.files("SSDM_TRIAL/FUTURE/",pattern=".asc",full.names=TRUE))
occ <- read.csv("SSDM_TRIAL/OCCURRENCE.csv")

algosdm <- modelling('MAXENT',Occurrences = occ, Env= pres, Xcol="lon",Ycol="lat",Pcol="Pres_abs")
proj <- project(algosdm,fut,output.format="rasters")
par(mfrow=c(1,2))
plot(algosdm@projection)
plot(proj$projection)

ensdm <- ensemble_modelling(c('CTA','MAXENT'),Occurrences = occ, Env= pres, Xcol="lon",Ycol="lat",Pcol="Pres_abs",rep=3)
enproj <- project(ensdm,fut,output.format="rasters")
```

**Comment by AJ-KBA** [comment] 2021-08-14 04:41
Dear Dr Lukas Baumbach: Thank you for your email. I ran my dataset with
your code and I still get the same error while using the MAXENT algorithm
but it works fine with other algorithms. I think the issue might be with
java on my system. I will run it on another system.

Thank you and best regards
Ashish Jha, PhD

**Closed** 2021-09-09 09:00 UTC
